// Add dpdk headers.
#define _GNU_SOURCE
#include <rte_eal.h>
#include <rte_ethdev.h>

// Bindgen cannot evaluate all RTE_BIT64 macro expansions. Enum initializers
// are evaluated by Clang and keep these masks tied to the installed headers.
enum {
    RPKT_RX_CHECKSUM_OFFLOADS = RTE_ETH_RX_OFFLOAD_IPV4_CKSUM | RTE_ETH_RX_OFFLOAD_UDP_CKSUM,
    RPKT_TX_CHECKSUM_OFFLOADS = RTE_ETH_TX_OFFLOAD_IPV4_CKSUM | RTE_ETH_TX_OFFLOAD_UDP_CKSUM
};

// Add wrapper definitions for functions that bindgen can not generate.
//
// For instance, static inline functions defined in c headers can not be
// generated by bindgen.
// 
// To generate bindings for static inline function, add a wrapper definition like:
//
// void wrapper_static_inline_function(void);
//
// Then, in the impl.c, implement the wrapper function with:
//
// void wrapper_static_inline_function(void) {
//    static_inline_function();
// }

unsigned rte_lcore_id_();

// Returns 0/1 for down/up, or a negative DPDK error.
int rte_eth_link_up_(uint16_t port_id);

int rte_mempool_full_(const struct rte_mempool *mp);

struct rte_mbuf *rte_pktmbuf_alloc_(struct rte_mempool *mp);

int rte_pktmbuf_alloc_bulk_(struct rte_mempool *pool,
							struct rte_mbuf **mbufs, unsigned count);

void rte_pktmbuf_free_(struct rte_mbuf *m);

uint16_t rte_eth_rx_burst_(uint16_t port_id, uint16_t queue_id,
						   struct rte_mbuf **rx_pkts, const uint16_t nb_pkts);

uint16_t rte_eth_tx_burst_(uint16_t port_id, uint16_t queue_id,
						   struct rte_mbuf **tx_pkts, uint16_t nb_pkts);

int rte_errno_();
